### ISSUE TITLE
Výsledky - nefunkční přepínání období

### ISSUE THREAD

**Issue by TENK14** [havit/Bonusario#13]
Pokud si na stránce výsledky přepnu v drop-downu na jiné období, tak se nenačte nový obsah a zůstane ten původní.

**Comment by hakenr** [comment]
Reprodukováno, dělají to výsledky, jak souhrnné, tak samostatné - tabulková forma.

**Comment by hakenr** [comment]
(Což je obecně použití HxGrid, kde neproběhne Refresh, pokud se změní vstupy.)
