### ISSUE TITLE
Možnost nastavení úrovně zveřejnění záznamů

### ISSUE THREAD

**Issue by crdo** [havit/Bonusario#21]
Chci mít možnost si při vkládání nového záznamu zvolit, zda je anonymní (výchozí), veřejný pro adresáta, nebo veřejný pro všechny.

- V případě anonymního vše zůstává, jak je
- V případě veřejného pro adresáta se u záznamu objeví, kdo ho vložil
- V případě veřejného pro všechny se nový záznam objeví na stránce Historie obdržených, kde budou nejdřív moje záznamy a následně záznamy ostatních

Dále bych chtěl, aby bylo možné si zvolit, jaký je výchozí stupeň veřejnosti pro každého uživatele, nějakým minimalistickým UI.

**Comment by Harvey1214** [comment]
@crdo Má se informace o veřejnosti záznamu zobrazovat v "Hromadném zadávání odměn" (/submission-table) v popoveru?
