### ISSUE TITLE
[AuthorIdentityVisibility] - code review

### ISSUE THREAD

**Issue by hakenr** [havit/Bonusario#22]
* [x] `AuthorIdentityVisibility` enum should be located in `Primitives` project (to be able to use it from `Model`), see NewProjectTemplate-Blazor
* [x] `Entry.AuthorIdentityVisibility` should be of type `AuthorIdentityVisibility` (enum) to better maintain consistency
* [x] `Entry.AuthorIdentityVisibility` should have explicit default value set (from the enum) to prevent security issues
* [x] `AuthorIdentityVisibility` enum should have explicit values set to prevent security issues (mapped to DB, should be constant "forever")
* [x] `EntrySeed` (demo-profile) should set `AuthorIdentityVisibility` + should contain examples of different visibilities for better testability
* [x] `Employee.DefaultIdentityVisibility` should be of type `AuthorIdentityVisibility` (enum) to better maintain consistency
* [x] `IEmployeeFacade` should work with `enum AuthorIdentityVisibility` not the `int`
* [x] EntryCard.razor - calling `CssClassHelper.Combine()` with single parameter does not make any sense (nothing to combine)
* [x] MyEntries.razor - `SetDefaultEntryAuthorIdentityVisibility` should have consistent naming to `Employee.DefaultIdentityVisibility` => `SetCurrentEmployeeDefaultIdentityVisibilityAsync` or `HandleDefaultIdentityVisibilityChanged`
* [x] EntryCard+MyEntriesFeed - not getting the dance around `defaultAuthorIdentityVisibility`, please explain

**Comment by Harvey1214** [comment]
> Entry.AuthorIdentityVisibility should have explicit default value set (from the enum) to prevent security issues

@hakenr not sure I understand this correctly, does the second commit resolve what you meant? (https://github.com/havit/Bonusario/commit/df824a3414c19a49bb2c29593478edbfaf429807) I don't know where else would I set the default, in the db table, default is 0 -> Hidden. Thanks for your help 😉.

**Comment by Harvey1214** [comment]
> EntryCard+MyEntriesFeed - not getting the dance around defaultAuthorIdentityVisibility, please explain

@hakenr MyEntriesFeed retrieves and sets EmployeeDefaultIdentityVisibility. EntryCard triggers a method on MyEntriesFeed when the "set default button" is pressed and disables the button when the default is selected.

Now thinking about it, I believe it may be more sensible to move all the DefaultIdentityVisibility logic to EntryCard and only set some boolean parameter on the component to indicate whether the "set default button" should be rendered. Please let me know what you think, thanks.

**Comment by hakenr** [comment]
lgtm
