### ISSUE TITLE
[UX] AuthorIdentityVisibility - nastavování výchozí viditelnosti

### ISSUE THREAD

**Issue by hakenr** [havit/Bonusario#23]
Asi bych tam dal confirmation, možná jinou ikonku, přijde mi to teď takový náchylný na chyby uživatele a ne úplně srozumitelný.
![image](https://user-images.githubusercontent.com/12828888/172376222-24c649a0-462b-47ce-9eef-b6809134a9ef.png)

@crdo, zkus něco zadat @Harvey1214, čím by se to trochu vyčistilo, dík.

**Comment by crdo** [comment]
Prosím změnit do této podoby:

1. Realizovat pomocí HxDropdown
2. Umístění pod vkládacím formulářem zarovnané s pravou hranou
3. Bude společný default (pro všechny) "viditelné pro příjemce", na úrovni uživatele nepůjde default nastavit

<img width="455" alt="image" src="https://user-images.githubusercontent.com/1410922/181771702-4494910a-6a29-4d84-9e43-18a8bbb2653d.png">

**Comment by Harvey1214** [comment]
> Bude společný default (pro všechny) "viditelné pro příjemce", na úrovni uživatele nepůjde default nastavit

Chceme tento default do appsettings, nebo stačí jako natvrdo konstanta do `EntryDto.DefaultVisibility`?
