### ISSUE TITLE
[UX] EntryCard - separate editing from viewing?

### ISSUE THREAD

**Issue by hakenr** [havit/Bonusario#24]
![image](https://user-images.githubusercontent.com/12828888/172395653-6d97a282-40e4-4b18-af26-5477ff240e51.png)
I suggest moving the editing to offcanvas/modal and keep the feed similar to Twitter (single column, etc.)
Adding new entries can be in-place (but not strictly necessary).

**Comment by crdo** [comment]
Vizuál pro tu readonly kartu dodám.

**Comment by crdo** [comment]
Záznamy nově budou vypadat takto.
Logika barev je 1-10 bronzová, 11-20 stříbrná, 21-100 zlatá.
Pokud na záznam kliknu, formulář se vyplní hodnotami a karta záznamu dostane 2px border v primary barvě.
<img width="675" alt="image" src="https://user-images.githubusercontent.com/1410922/189092116-e6cad895-cffa-459c-aaea-333c7e5f7657.png">

**Comment by hakenr** [comment]
Jo my to tím vlastně chceme ještě prezentovat "ostatním". To je samozřejmě trochu matoucí, že by tam bylo 10 zlatých ode mě a vedle toho 10 stříbrných od tebe. Hmm, tak nevim. Přijde mi, že ty barvy do toho vnášejí nějaký ukotvení. Jako v Qerku, že ti nabízejí tipsy 5% / 10% / 15% a ještě k tomu interpretují ksichtík. (Já dávám 0% a objevuje se tam plačící smajlík. :-D)

**Comment by crdo** [comment]
Můžeme to udělat neutrální, nebo jednobarevný. Chtěl jsem do toho vnést trochu života, ale nutný to určitě není.

**Comment by crdo** [comment]
Původně sem chtěl jen minci, ty barvy vznikly nějak samovolně...

**Comment by hakenr** [comment]
Ono je to vizuálně hezký, o tom žádná. Jen trochu ukotvující, co se interpretace těch čísel týče.
Ještě by se dala udělat nějaká absolutní škála s počítaným odstínem. Prostě to počítat jako barevný přechod mezi zlatou (100 bodů) a stříbrnou (0 bodů). Nebo prostě mezi dvěma barvami a spočítat něco mezi.

Asi by nebylo těžký to nastavovat jako opacity něčeho nad něčím jiným, ne?

**Comment by Harvey1214** [comment]
Na jakém určování barvy mince jsme tedy skončili?

Navrženy byly tyto možnosti:

- konstantní - barva je vždy stejná
- gradient (0 bodů - stříbrná, 100 bodů zlatá)
- pevně určené rozsahy (1-10 bronzová, 11-20 stříbrná, 21-100 zlatá)
- relativně určené rozsahy dle obdržených záznamů v období (spodní 1/3 bronzová, prostředí 1/3 stříbrná, horní 1/3 zlatá)

Aktuálně je barva vždy stejná.
