### ISSUE TITLE
Code-review: IEntryRepository.GetEntriesOfPeriod() - nekorektní komentář

### ISSUE THREAD

**Issue by hakenr** [havit/Bonusario#29]
https://github.com/havit/Bonusario/blob/4573b26bcaf512218f08141039001d80668cad0e/DataLayer/Repositories/IEntryRepository.cs#L12-L18

...takto by komentáře dopadat neměly (prázdné; summary neobsahuje význam metody, atp.)

**Comment by hakenr** [comment]
Neměly by tam zůstávat ani ty prázdné komentáře k parametrům, to je radši vyhoď.

**Comment by Harvey1214** [comment]
https://github.com/havit/Bonusario/commit/ad040316e9d9012e5297ae965f55d9cb7c27b793
