### ISSUE TITLE
MyEntriedFeed - podněty k UX a zjednodušení

### ISSUE THREAD

**Issue by hakenr** [havit/Bonusario#32]
Podněty k diskuzi s @crdo 
1. Zrušení editace bych dělal nějaký křížkem (třeba offcanvas/modal, nebo u tlačítek), ne klikáním mimo. Ušetří to navíc JScript.
2. Editaci bych dělal in-place, tj. vyměnil bych ReadOnlyEntryCard za EntryCard v tom místě, kde je. Tím se ušetří navíc JScript pro scrollování.
3. Uspořádání údajů v ReadOnlyEntryCard a EntryCard bych udělal podobné. Ruší mě, když kliknu editaci a počet bodů je na kartě najednou jinde. (Je mi jedno, jestli to bude obojí vlebo, obojí vpravo, nebo jestli se na to vykašlete. Jenom hlásím, že mě to teď mate.)

**Comment by crdo** [comment]
Hotovo v posledním release.
