### ISSUE TITLE
[Feature] Samostatné scrollování prostřední sekce

### ISSUE THREAD

**Issue by crdo** [havit/Bonusario#37]
Chtěl bych, aby měl prostředek samostatný scrollbar, takže navigace a postranní panel s přehledem zůstanou na místě.
Nadpis stránky a formulář pro vkládání by taky mohl být sticky.
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/1410922/215748695-53d3a2ce-a8da-47c0-af54-4c3d3bf95e1b.png">

**Comment by crdo** [comment]
Na mobile to zůstane as-is.

**Comment by hakenr** [comment]
Přijde mi, že toto nefunguje, pořád mi to scrolluje i pravý sloupec.
cc @crdo @Harvey1214

**Comment by Harvey1214** [comment]
Děkuji za upozornění, rozbilo se nám to s přidáním záložek, opravím.

**Comment by Harvey1214** [comment]
@crdo, opraveno. Snažil jsem se zbavit se hardcodované hodnoty pro výšku elementu s třídou `entries` pomocí flexboxu, ale nefungovalo tam `flex-shrink`, element se nezmenšil, aby se vešel do parent elementu s `d-flex flex-column`, nevíš čím by to mohlo být?

**Comment by crdo** [comment]
Musel bych vidět live před sebou...

**Comment by crdo** [comment]
V pátek mi to ukážeš.

**Comment by Harvey1214** [comment]
Jasně, není problém.

**Comment by Harvey1214** [comment]
![image](https://github.com/havit/Bonusario/assets/62853076/a7803642-5020-45ed-8fde-ac84fe960308)
