### ISSUE TITLE
[BUG] Po editaci karty hodnoty zůstanou, pokud jsem nedal uložit

### ISSUE THREAD

**Issue by TENK14** [havit/Bonusario#38]
Pokud zedituji kartu a místo kliku na Uložit kliknu jinam, tak se editace dané karty zruší a nové hodnoty v ní zůstanou, což evokuje, že se hodnoty přesto uložily, což není pravda. (Při pozdějším uložení v jiné kartě se data všech karet zaktualizují.)

Cc @Harvey1214

**Comment by hakenr** [comment]
@Harvey1214, je potřeba pro editační komponentu model nejprve vyklonovat, editovat nad klonem a pak při uložení updatovat původní instanci z klonu. Viz GOR-G3 a podobné projekty, jak to tam je při editaci List+Edit.

**Comment by hakenr** [comment]
@Harvey1214 Ten clonning constructor, co si tam udělal, ten ti vyrobí C#, když použiješ `record`.
Pak místo `editedEntry = new Entry(entry);` použiješ `editedEntry = entry with {};`. Zápis je to trochu zvláštní, ale nemusíš pak s každou přidanou property dopisovat constructor.
