### ISSUE TITLE
Výsledková listina

### ISSUE THREAD

**Issue by hakenr** [havit/Bonusario#4]

**Comment by crdo** [comment]
Pro dané období (Period) chci mít možnost zobrazit tabulku všech zaměstnanců a jim přidělených odměn a tagů v daném období.
Seřazeno dle příjmení.

**Comment by hakenr** [comment]
Neevidujeme samostatně příjmení, jen celé jméno.
Nějaké minimum jsem tam nahodil, zatím bez tagů.

**Comment by TENK14** [comment]
Drop-down mi nenabízí předchozí období, pouze aktuální měsíc.

**Comment by hakenr** [comment]
@TENK14
Výsledky (/results) mi nabízejí 10/2021, možná se mezi tím změnilo nastavení, nicméně problém podle mě už netrvá.
(Zobrazit, co jsem komu dal, to je legitimní, ale zadávám to jako samostatné issue.)

(I ty tagy zadám samostatně, ať nenabalujeme na tento issue další věci.)
