### ISSUE TITLE
[Feature] Rozdělit nastavení viditelnosti a podpisu

### ISSUE THREAD

**Issue by crdo** [havit/Bonusario#40]
Po zpětné vazby od uživatelů po nasazení této feature to potřebuji rozdělit - je to pro ně matoucí.

### Výchozí nastavení:
S podpisem = true
Viditelnost = pro příjemce

### UI as is:
![Image](https://user-images.githubusercontent.com/1410922/216310918-e770e7af-13c6-4537-9f3f-2179c767ac6e.png)

### UI todo
![Image](https://user-images.githubusercontent.com/1410922/216310439-63ef8aff-c7e5-4c77-93c5-1de306e3cb26.png)

**Pozor na to, že budeme muset udělat adekvátní migraci historických dat.**

**Comment by hakenr** [comment]
Jaké budou defaulty? Nastavitelné?
Není "viditelné všem" taky jen switch? (příjemci je to viditelné vždy, jen buď s podpisem nebo bez)

**Comment by crdo** [comment]
Defaulty jsou uvedené výše.
Viditelné všem asi switch být může, ale když už je tam ten hezký dropdown 😆

**Comment by Harvey1214** [comment]
Přímo do root složky repozitáře jsem připravil SQL skript pro transformaci dat, který bude potřeba spustit nad produkční databází po nasazení nové verze aplikace.

**Comment by hakenr** [comment]
> Přímo do root složky repozitáře jsem připravil SQL skript pro transformaci dat, který bude potřeba spustit nad produkční databází po nasazení nové verze aplikace.

Je potřeba to udělat jako EF Core migration, aby se to nepouštělo ručně, ale aplikovalo automaticky. Ukážu ti to.
https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli

**Comment by Harvey1214** [comment]
Přidal jsem transformaci dat do migrace, která přidává sloupce Public a Signed do tabulky Entry.

**Comment by hakenr** [comment]
@Harvey1214 ještě mi tam chybí drop toho sloupce Visibility, to už dej do nové migrace (neseděl by model u migrace, kdybys to přidal do té původní).

**Comment by crdo** [comment]
@Harvey1214 ještě tam touto úpravou vznikla možnost vložit anonymního záznamu, viditelného pro všechny. To budeme muset nějak vyřešit - není to žádané.
