### ISSUE TITLE
[BUG] NullReferenceException z GivenPointsSummary.LoadData()

### ISSUE THREAD

**Issue by hakenr** [havit/Bonusario#45]
![image](https://user-images.githubusercontent.com/12828888/235314382-6f0e7d2d-8755-41ac-86e0-9da91538b439.png)

**Comment by hakenr** [comment]
Udělalo mi to ihned po načtení, reload to "vyřešil" a už se to neobjevuje.
Myslím, že už jsem to párkrát viděl i předchozí měsíce.
Bude to nějaký async order issue, tipuji.

**Comment by Harvey1214** [comment]
@crdo, mělo by to být v pořádku, zkoušel jsem to na stage.
